[2023-07-08 13:46:07,554: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-08 13:46:07,558: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-08 13:46:07,558: INFO: common: created directory at: artifacts]
[2023-07-08 13:46:07,563: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-08 13:48:22,085: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-08 13:48:22,093: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-08 13:48:22,096: INFO: common: created directory at: artifacts]
[2023-07-08 13:48:22,096: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-08 13:49:06,594: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-08 13:49:06,600: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-08 13:49:06,600: INFO: common: created directory at: artifacts]
[2023-07-08 13:49:06,600: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-08 13:49:54,360: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-08 13:49:54,363: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-08 13:49:54,363: INFO: common: created directory at: artifacts]
[2023-07-08 13:49:54,368: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-10 09:24:00,640: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-10 09:24:00,664: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-10 09:24:00,672: INFO: common: created directory at: artifacts]
[2023-07-10 09:24:00,672: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-10 09:24:05,768: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-10 09:24:05,775: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-10 09:24:05,776: INFO: common: created directory at: artifacts]
[2023-07-10 09:24:05,779: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-10 09:25:18,231: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-10 09:25:18,239: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-10 09:25:18,239: INFO: common: created directory at: artifacts]
[2023-07-10 09:25:18,239: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-10 15:47:05,515: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-10 15:47:05,521: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-10 15:47:05,521: INFO: common: created directory at: artifacts]
[2023-07-10 15:47:05,521: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-10 23:37:28,250: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-10 23:37:28,260: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-10 23:37:28,262: INFO: common: created directory at: artifacts]
[2023-07-10 23:37:28,263: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-11 00:07:37,761: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-11 00:07:37,769: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-11 00:07:37,769: INFO: common: created directory at: artifacts]
[2023-07-11 00:07:37,769: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-11 00:07:37,769: INFO: 2671438034: File already exists of size: ~ 2405630 KB]
[2023-07-11 00:24:56,914: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-11 00:24:56,917: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-11 00:24:56,919: INFO: common: created directory at: artifacts]
[2023-07-11 00:24:56,920: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-11 00:24:56,921: INFO: 2671438034: File already exists of size: ~ 2405630 KB]
[2023-07-11 00:29:53,711: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-11 00:29:53,714: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-11 00:29:53,717: INFO: common: created directory at: artifacts]
[2023-07-11 00:29:53,717: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-11 00:29:53,722: INFO: 2671438034: File already exists of size: ~ 2405630 KB]
[2023-07-11 00:30:23,098: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-11 00:30:23,100: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-11 00:30:23,100: INFO: common: created directory at: artifacts]
[2023-07-11 00:30:23,107: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-11 00:30:23,108: INFO: 2671438034: File already exists of size: ~ 2405630 KB]
[2023-07-11 00:46:39,849: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-11 00:46:39,857: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-11 00:46:39,860: INFO: common: created directory at: artifacts]
[2023-07-11 00:46:39,860: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-11 00:46:39,865: INFO: 2671438034: File already exists of size: ~ 2405630 KB]
[2023-07-11 00:48:35,235: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-11 00:48:35,243: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-11 00:48:35,243: INFO: common: created directory at: artifacts]
[2023-07-11 00:48:35,243: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-11 00:48:35,243: INFO: 2671438034: File already exists of size: ~ 2405630 KB]
[2023-07-11 00:58:53,878: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-11 00:58:53,882: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-11 00:58:53,882: INFO: common: created directory at: artifacts]
[2023-07-11 00:58:53,882: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-11 00:58:53,886: INFO: 2671438034: File already exists of size: ~ 2405630 KB]
[2023-07-11 01:03:23,876: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-11 01:03:23,884: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-11 01:03:23,884: INFO: common: created directory at: artifacts]
[2023-07-11 01:03:23,890: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-11 01:03:23,892: INFO: 3108789274: File already exists of size: ~ 2405630 KB]
[2023-07-11 01:04:34,216: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-11 01:04:34,224: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-11 01:04:34,224: INFO: common: created directory at: artifacts]
[2023-07-11 01:04:34,228: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-11 01:04:34,228: INFO: 3108789274: File already exists of size: ~ 2405630 KB]
[2023-07-11 01:05:52,089: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-11 01:05:52,089: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-11 01:05:52,097: INFO: common: created directory at: artifacts]
[2023-07-11 01:05:52,097: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-11 01:05:52,097: INFO: 3108789274: File already exists of size: ~ 2405630 KB]
[2023-07-11 01:11:03,377: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-11 01:11:03,393: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-11 01:11:03,393: INFO: common: created directory at: artifacts]
[2023-07-11 01:11:03,399: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-11 01:11:03,399: INFO: 3108789274: File already exists of size: ~ 2405630 KB]
[2023-07-11 01:14:34,547: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-11 01:14:34,550: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-11 01:14:34,555: INFO: common: created directory at: artifacts]
[2023-07-11 01:14:34,555: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-11 01:14:34,560: INFO: 2671438034: File already exists of size: ~ 2405630 KB]
[2023-07-12 12:23:42,752: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-12 12:23:42,761: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-12 12:23:42,762: INFO: common: created directory at: artifacts]
[2023-07-12 12:23:42,764: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-12 12:23:42,766: INFO: 2671438034: File already exists of size: ~ 2405630 KB]
[2023-07-12 12:27:49,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-12 12:27:49,683: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-12 12:27:49,685: INFO: common: created directory at: artifacts]
[2023-07-12 12:27:49,685: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-12 12:27:49,685: INFO: 2671438034: File already exists of size: ~ 2405630 KB]
[2023-07-12 12:30:38,997: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-12 12:30:39,000: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-12 12:30:39,003: INFO: common: created directory at: artifacts]
[2023-07-12 12:30:39,005: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-12 12:30:39,006: INFO: 2671438034: File already exists of size: ~ 2405630 KB]
[2023-07-12 12:33:37,461: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-12 12:33:37,465: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-12 12:33:37,466: INFO: common: created directory at: artifacts]
[2023-07-12 12:33:37,468: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-12 12:34:59,249: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-12 12:34:59,253: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-12 12:34:59,255: INFO: common: created directory at: artifacts]
[2023-07-12 12:34:59,256: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-12 12:38:18,145: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-12 12:38:18,148: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-12 12:38:18,150: INFO: common: created directory at: artifacts]
[2023-07-12 12:38:18,151: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-12 12:38:28,541: INFO: 1226982078: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 9F04:36C8:C356:F441:64AE5160
Accept-Ranges: bytes
Date: Wed, 12 Jul 2023 07:08:19 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100024-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1689145697.790493,VS0,VE2270
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 073a6ff80de3057439a6e8fca4fa324380c48270
Expires: Wed, 12 Jul 2023 07:13:19 GMT
Source-Age: 2

]
[2023-07-12 12:49:44,280: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-12 12:49:44,283: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-12 12:49:44,284: INFO: common: created directory at: artifacts]
[2023-07-12 12:49:44,285: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-13 22:57:57,934: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-13 22:57:57,946: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-13 22:57:57,951: INFO: common: created directory at: artifacts]
[2023-07-13 22:57:57,952: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-18 16:47:56,892: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-18 16:47:56,913: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-18 16:47:56,916: INFO: common: created directory at: artifacts]
[2023-07-18 16:47:56,917: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-18 16:53:31,225: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-18 16:53:31,231: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-18 16:53:31,231: INFO: common: created directory at: artifacts]
[2023-07-18 16:53:31,231: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-18 16:53:31,231: INFO: 1226982078: File already exists of size: ~ 2405630 KB]
[2023-07-18 16:56:29,665: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-18 16:56:29,671: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-18 16:56:29,671: INFO: common: created directory at: artifacts]
[2023-07-18 17:00:58,218: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-18 17:00:58,227: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-18 17:00:58,227: INFO: common: created directory at: artifacts]
[2023-07-18 17:00:58,227: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-18 17:00:58,227: INFO: 1226982078: File already exists of size: ~ 2405630 KB]
[2023-07-19 13:04:25,412: INFO: main: >>>>>>> Stage Data Ingestion Stage Started <<<<<<<]
[2023-07-19 13:04:25,420: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-19 13:04:25,428: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-19 13:04:25,428: INFO: common: created directory at: artifacts]
[2023-07-19 13:04:25,428: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-19 13:04:25,436: INFO: data_ingestion: File already exists of size: ~ 2405630 KB]
[2023-07-19 13:05:04,815: INFO: main: >>>>>>> Stage Data Ingestion Stage Completed <<<<<<</n/nx====================x]
[2023-07-20 17:26:45,047: INFO: main: >>>>>>> Stage Data Ingestion Stage Started <<<<<<<]
[2023-07-20 17:26:45,069: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 17:26:45,085: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 17:26:45,093: INFO: common: created directory at: artifacts]
[2023-07-20 17:26:45,093: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-20 17:26:45,093: INFO: data_ingestion: File already exists of size: ~ 2405630 KB]
[2023-07-20 17:27:33,509: INFO: main: >>>>>>> Stage Data Ingestion Stage Completed <<<<<<</n/nx====================x]
[2023-07-20 18:29:31,257: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 18:29:31,260: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 18:29:31,261: INFO: common: created directory at: artifacts]
[2023-07-20 18:29:31,262: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-20 18:29:31,264: INFO: 1226982078: File already exists of size: ~ 2405630 KB]
[2023-07-20 18:30:01,178: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 18:30:01,180: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 18:30:01,181: INFO: common: created directory at: artifacts]
[2023-07-20 18:33:06,525: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 18:33:06,528: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 18:33:06,529: INFO: common: created directory at: artifacts]
[2023-07-20 18:33:06,531: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-07-20 18:33:48,544: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 18:33:48,548: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 18:33:48,549: INFO: common: created directory at: artifacts]
[2023-07-20 18:33:48,550: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-07-20 18:34:03,874: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 18:34:03,877: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 18:34:03,879: INFO: common: created directory at: artifacts]
[2023-07-20 18:34:03,880: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-07-20 18:35:35,964: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 18:35:35,968: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 18:35:35,970: INFO: common: created directory at: artifacts]
[2023-07-20 18:35:35,971: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-07-20 18:35:40,794: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 18:35:40,798: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 18:35:40,799: INFO: common: created directory at: artifacts]
[2023-07-20 18:36:04,466: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 18:36:04,470: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 18:36:04,472: INFO: common: created directory at: artifacts]
[2023-07-20 18:36:04,473: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-07-20 18:37:11,830: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 18:37:11,835: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 18:37:11,837: INFO: common: created directory at: artifacts]
[2023-07-20 18:37:11,838: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-07-20 20:29:54,710: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:29:54,725: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 20:29:54,733: INFO: common: created directory at: artifacts]
[2023-07-20 20:29:54,741: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-07-20 20:30:32,632: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:30:32,640: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 20:30:32,640: INFO: common: created directory at: artifacts]
[2023-07-20 20:30:32,640: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-07-20 20:30:34,408: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-07-20 20:33:29,414: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:33:29,422: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 20:33:29,428: INFO: common: created directory at: artifacts]
[2023-07-20 20:33:29,430: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-20 20:33:29,434: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-20 20:35:04,785: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:35:04,793: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 20:35:04,793: INFO: common: created directory at: artifacts]
[2023-07-20 20:35:04,793: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-20 20:35:04,804: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-20 20:35:04,813: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:35:04,817: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 20:35:04,817: INFO: common: created directory at: artifacts]
[2023-07-20 20:35:04,817: INFO: common: created directory at: artifacts\training]
[2023-07-20 20:36:10,826: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:36:10,837: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 20:36:10,840: INFO: common: created directory at: artifacts]
[2023-07-20 20:36:10,841: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-20 20:36:10,841: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-20 20:36:10,841: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-20 20:36:10,851: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-20 20:36:10,851: INFO: common: created directory at: artifacts]
[2023-07-20 20:36:10,851: INFO: common: created directory at: artifacts\training]
[2023-07-21 19:11:21,310: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-21 19:11:21,330: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-21 19:11:21,334: INFO: common: created directory at: artifacts]
[2023-07-21 19:11:21,334: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-21 19:11:21,342: INFO: 2631307968: File already exists of size: ~ 2405630 KB]
[2023-07-22 12:25:03,122: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 12:25:03,126: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 12:25:03,126: INFO: common: created directory at: artifacts]
[2023-07-22 12:25:03,133: INFO: common: created directory at: artifacts\training]
[2023-07-22 12:26:03,686: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 12:26:03,694: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 12:26:03,694: INFO: common: created directory at: artifacts]
[2023-07-22 12:26:03,701: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 12:26:03,703: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 12:26:03,708: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 12:26:03,713: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 12:26:03,713: INFO: common: created directory at: artifacts]
[2023-07-22 12:26:03,713: INFO: common: created directory at: artifacts\training]
[2023-07-22 12:28:08,151: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 12:28:08,155: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 12:28:08,160: INFO: common: created directory at: artifacts]
[2023-07-22 12:28:08,163: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 12:28:08,167: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 12:28:08,174: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 12:28:08,176: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 12:28:08,179: INFO: common: created directory at: artifacts]
[2023-07-22 12:28:08,182: INFO: common: created directory at: artifacts\training]
[2023-07-22 12:28:55,335: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 12:28:55,342: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 12:28:55,343: INFO: common: created directory at: artifacts]
[2023-07-22 12:28:55,345: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 12:28:55,345: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 12:28:55,349: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 12:28:55,356: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 12:28:55,356: INFO: common: created directory at: artifacts]
[2023-07-22 12:28:55,356: INFO: common: created directory at: artifacts\training]
[2023-07-22 12:29:59,885: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 12:29:59,889: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 12:29:59,897: INFO: common: created directory at: artifacts]
[2023-07-22 12:29:59,899: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 12:29:59,899: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 12:29:59,905: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 12:29:59,905: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 12:29:59,913: INFO: common: created directory at: artifacts]
[2023-07-22 12:29:59,915: INFO: common: created directory at: artifacts\training]
[2023-07-22 12:51:35,174: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 12:51:35,183: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 12:51:35,184: INFO: common: created directory at: artifacts]
[2023-07-22 12:51:35,190: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 12:51:35,192: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 12:51:35,193: INFO: common: created directory at: artifacts\training]
[2023-07-22 15:37:25,040: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 15:37:25,050: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 15:37:25,056: INFO: common: created directory at: artifacts]
[2023-07-22 15:37:25,058: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 15:37:25,061: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 15:37:25,073: INFO: common: created directory at: artifacts\training]
[2023-07-22 15:40:19,599: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 15:40:19,602: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 15:40:19,606: INFO: common: created directory at: artifacts]
[2023-07-22 15:40:19,608: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 15:40:19,608: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 15:40:19,613: INFO: common: created directory at: artifacts\training]
[2023-07-22 17:36:23,621: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 17:36:23,627: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 17:36:23,634: INFO: common: created directory at: artifacts]
[2023-07-22 17:36:23,635: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 17:36:23,635: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 17:36:23,635: INFO: common: created directory at: artifacts\training]
[2023-07-22 17:36:54,668: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 17:36:54,680: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 17:36:54,689: INFO: common: created directory at: artifacts]
[2023-07-22 17:36:54,689: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 17:36:54,689: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 17:36:54,689: INFO: common: created directory at: artifacts\training]
[2023-07-22 17:39:20,881: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 17:39:21,118: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 17:39:21,118: INFO: common: created directory at: artifacts]
[2023-07-22 17:39:21,118: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 17:39:21,124: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 17:39:21,127: INFO: common: created directory at: artifacts\training]
[2023-07-22 19:10:30,290: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 19:10:30,305: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 19:10:30,307: INFO: common: created directory at: artifacts]
[2023-07-22 19:10:30,315: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 19:10:30,317: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 19:10:30,333: INFO: common: created directory at: artifacts\training]
[2023-07-22 19:25:17,723: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 19:25:17,746: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 19:25:17,748: INFO: common: created directory at: artifacts]
[2023-07-22 19:25:17,749: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 19:25:17,749: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 19:25:17,758: INFO: common: created directory at: artifacts\training]
[2023-07-22 19:27:15,097: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 19:27:15,102: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 19:27:15,102: INFO: common: created directory at: artifacts]
[2023-07-22 19:27:15,107: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 19:27:15,108: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 19:27:15,110: INFO: common: created directory at: artifacts\training]
[2023-07-22 20:09:47,469: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 20:09:47,482: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 20:09:47,485: INFO: common: created directory at: artifacts]
[2023-07-22 20:09:47,494: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 20:09:47,494: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 20:09:47,510: INFO: common: created directory at: artifacts\training]
[2023-07-22 20:25:06,211: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-22 20:25:06,224: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-22 20:25:06,228: INFO: common: created directory at: artifacts]
[2023-07-22 20:25:06,231: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-22 20:25:06,232: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-22 20:25:06,232: INFO: common: created directory at: artifacts\training]
[2023-07-23 15:20:58,859: INFO: main: >>>>>>> Stage Data Ingestion Stage Started <<<<<<<]
[2023-07-23 15:20:58,859: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-23 15:20:58,870: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-23 15:20:58,870: INFO: common: created directory at: artifacts]
[2023-07-23 15:20:58,870: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-23 15:20:58,872: INFO: data_ingestion: File already exists of size: ~ 2405630 KB]
[2023-07-23 15:21:28,838: INFO: main: >>>>>>> Stage Data Ingestion Stage Completed <<<<<<</n/nx====================x]
[2023-07-23 15:21:28,838: INFO: main: ************************]
[2023-07-23 15:21:28,838: INFO: main: >>>>>>> Stage Training Stage Started <<<<<<<]
[2023-07-23 15:21:28,838: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-23 15:21:28,838: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-23 15:21:28,838: INFO: common: created directory at: artifacts]
[2023-07-23 15:21:28,838: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-23 15:21:28,838: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-23 15:21:28,838: INFO: common: created directory at: artifacts\training]
[2023-07-23 15:21:28,848: ERROR: main: "'ConfigBox' object has no attribute 'augmentation'"]
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'AUGMENTATION'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'AUGMENTATION'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'AUGMENTATION'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'AUGMENTATION'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'augmentation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'augmentation'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'augmentation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Programs\xray\main.py", line 26, in <module>
    obj.main()
  File "C:\Programs\xray\src\xray\pipeline\training_pipeline.py", line 18, in main
    training_config = config.get_training_config()
  File "C:\Programs\xray\src\xray\config\configuration.py", line 90, in get_training_config
    params_is_augmentation=params.AUGMENTATION,
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'augmentation'"
[2023-07-23 15:23:01,051: INFO: main: >>>>>>> Stage Data Ingestion Stage Started <<<<<<<]
[2023-07-23 15:23:01,053: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-23 15:23:01,053: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-23 15:23:01,053: INFO: common: created directory at: artifacts]
[2023-07-23 15:23:01,053: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-23 15:23:01,053: INFO: data_ingestion: File already exists of size: ~ 2405630 KB]
[2023-07-23 15:23:31,199: INFO: main: >>>>>>> Stage Data Ingestion Stage Completed <<<<<<</n/nx====================x]
[2023-07-23 15:23:31,199: INFO: main: ************************]
[2023-07-23 15:23:31,199: INFO: main: >>>>>>> Stage Training Stage Started <<<<<<<]
[2023-07-23 15:23:31,199: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-23 15:23:31,199: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-23 15:23:31,199: INFO: common: created directory at: artifacts]
[2023-07-23 15:23:31,199: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-23 15:23:31,199: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-23 15:23:31,199: INFO: common: created directory at: artifacts\training]
[2023-07-23 16:06:26,874: INFO: main: >>>>>>> Stage Training Stage Completed <<<<<<<

x====================x]
[2023-07-23 16:15:44,102: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.231.107:8080]
[2023-07-23 16:15:44,102: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-23 16:15:57,705: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:15:57] "GET / HTTP/1.1" 200 -]
[2023-07-23 16:16:41,221: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 39, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Programs\xray\src\xray\pipeline\predict.py", line 18, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img'
[2023-07-23 16:16:41,271: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:16:41] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-23 16:18:11,288: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:18:11] "GET / HTTP/1.1" 200 -]
[2023-07-23 16:18:17,602: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 39, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Programs\xray\src\xray\pipeline\predict.py", line 18, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img'
[2023-07-23 16:18:17,608: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:18:17] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-23 16:19:14,418: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.231.107:8080]
[2023-07-23 16:19:14,418: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-23 16:19:24,413: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:19:24] "GET / HTTP/1.1" 200 -]
[2023-07-23 16:19:30,484: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 39, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Programs\xray\src\xray\pipeline\predict.py", line 18, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img'
[2023-07-23 16:19:30,484: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:19:30] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-23 16:21:17,966: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:21:17] "GET / HTTP/1.1" 200 -]
[2023-07-23 16:21:24,183: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 39, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Programs\xray\src\xray\pipeline\predict.py", line 18, in predict
    test_image = load_img(imagename, target_size = (224,224))
AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img'
[2023-07-23 16:21:24,200: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:21:24] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-23 16:21:34,300: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.231.107:8080]
[2023-07-23 16:21:34,300: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-23 16:21:36,947: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:21:36] "GET / HTTP/1.1" 200 -]
[2023-07-23 16:21:47,932: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 39, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Programs\xray\src\xray\pipeline\predict.py", line 21, in predict
    result = np.argmax(model.predict(test_image), axis=1)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\SANDES~1\AppData\Local\Temp\__autograph_generated_filetio7hcc1.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 2111, in predict_step
        return self(x, training=False)
    File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 150, 150, 3), found shape=(None, 224, 224, 3)

[2023-07-23 16:21:47,936: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:21:47] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-23 16:22:21,771: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.231.107:8080]
[2023-07-23 16:22:21,771: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-23 16:22:24,481: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:22:24] "GET / HTTP/1.1" 200 -]
[2023-07-23 16:22:33,581: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:22:33] "POST /predict HTTP/1.1" 200 -]
[2023-07-23 16:22:48,448: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:22:48] "POST /predict HTTP/1.1" 200 -]
[2023-07-23 16:22:56,532: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:22:56] "POST /predict HTTP/1.1" 200 -]
[2023-07-23 16:23:03,064: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:23:03] "POST /predict HTTP/1.1" 200 -]
[2023-07-23 16:23:13,866: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002FB66420550> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-07-23 16:23:13,866: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:23:13] "POST /predict HTTP/1.1" 200 -]
[2023-07-23 16:23:26,408: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002FB66421630> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-07-23 16:23:26,408: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:23:26] "POST /predict HTTP/1.1" 200 -]
[2023-07-23 16:24:29,962: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.231.107:8080]
[2023-07-23 16:24:29,962: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-23 16:24:32,506: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:24:32] "GET / HTTP/1.1" 200 -]
[2023-07-23 16:24:38,628: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:24:38] "POST /predict HTTP/1.1" 200 -]
[2023-07-23 16:24:51,181: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:24:51] "POST /predict HTTP/1.1" 200 -]
[2023-07-23 16:26:07,994: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.231.107:8080]
[2023-07-23 16:26:07,994: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-23 16:26:11,777: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:26:11] "GET / HTTP/1.1" 200 -]
[2023-07-23 16:26:19,328: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 39, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Programs\xray\src\xray\pipeline\predict.py", line 21, in predict
    result = np.argmax(model.predict(test_image), axis=1)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\SANDES~1\AppData\Local\Temp\__autograph_generated_filesb68n4un.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 2111, in predict_step
        return self(x, training=False)
    File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 150, 150, 3), found shape=(None, 150, 3)

[2023-07-23 16:26:19,328: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:26:19] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-23 16:26:47,870: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.231.107:8080]
[2023-07-23 16:26:47,870: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-23 16:26:50,812: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:26:50] "GET / HTTP/1.1" 200 -]
[2023-07-23 16:27:00,014: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:27:00] "POST /predict HTTP/1.1" 200 -]
[2023-07-23 16:28:04,375: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.231.107:8080]
[2023-07-23 16:28:04,375: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-23 16:28:06,666: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:28:06] "GET / HTTP/1.1" 200 -]
[2023-07-23 16:28:17,126: INFO: _internal: 127.0.0.1 - - [23/Jul/2023 16:28:17] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 16:43:02,671: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 16:43:02,671: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 16:43:48,643: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 16:43:48] "GET / HTTP/1.1" 200 -]
[2023-07-24 16:44:03,486: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 16:44:03] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 18:06:42,033: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 18:06:42,036: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 18:06:58,970: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 18:06:58] "GET / HTTP/1.1" 200 -]
[2023-07-24 18:07:10,850: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 38, in predictRoute
    decodeImage(image, clApp.filename)
  File "C:\Programs\xray\src\xray\utils\common.py", line 136, in decodeImage
    f.write(imgdata)
TypeError: a bytes-like object is required, not 'NoneType'
[2023-07-24 18:07:10,877: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 18:07:10] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-24 18:20:58,790: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 18:20:58,790: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 18:21:03,243: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 18:21:03] "GET / HTTP/1.1" 200 -]
[2023-07-24 18:21:14,662: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 38, in predictRoute
    decodeImage(image, clApp.filename)
  File "C:\Programs\xray\src\xray\utils\common.py", line 136, in decodeImage
    f.write(imgdata)
TypeError: a bytes-like object is required, not 'NoneType'
[2023-07-24 18:21:14,665: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 18:21:14] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-24 18:22:51,739: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 18:22:51,739: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 18:22:54,039: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 18:22:54] "GET / HTTP/1.1" 200 -]
[2023-07-24 18:23:00,590: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 39, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Programs\xray\src\xray\pipeline\predict.py", line 21, in predict
    img = cv2.resize(img, (150,150))
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

[2023-07-24 18:23:00,592: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 18:23:00] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-24 18:26:47,138: INFO: main: >>>>>>> Stage Data Ingestion Stage Started <<<<<<<]
[2023-07-24 18:26:47,142: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-24 18:26:47,145: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-24 18:26:47,147: INFO: common: created directory at: artifacts]
[2023-07-24 18:26:47,147: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-24 18:26:47,147: INFO: data_ingestion: File already exists of size: ~ 2405630 KB]
[2023-07-24 18:27:17,411: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 18:27:17,411: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 18:27:21,589: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 18:27:21] "GET / HTTP/1.1" 200 -]
[2023-07-24 18:27:27,823: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 18:27:27] "[31m[1mPOST /predict HTTP/1.1[0m" 400 -]
[2023-07-24 18:31:20,821: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 18:31:20,821: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 18:31:23,879: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 18:31:23] "GET / HTTP/1.1" 200 -]
[2023-07-24 18:31:29,884: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 18:31:29] "[31m[1mPOST /predict HTTP/1.1[0m" 400 -]
[2023-07-24 18:32:54,090: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 18:32:54,090: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 18:32:56,043: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 18:32:56] "GET / HTTP/1.1" 200 -]
[2023-07-24 18:33:05,565: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 18:33:05] "[31m[1mPOST /predict HTTP/1.1[0m" 400 -]
[2023-07-24 19:24:08,725: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 19:24:08,725: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 19:24:12,841: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:24:12] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:24:20,342: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:24:20] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:26:15,260: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 19:26:15,260: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 19:26:17,809: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:26:17] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:26:24,507: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:26:24] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:27:10,860: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:27:10] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:27:18,422: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:27:18] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:27:38,836: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 19:27:38,836: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 19:27:40,685: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:27:40] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:27:52,562: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:27:52] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:27:59,248: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:27:59] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:29:08,871: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 19:29:08,871: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 19:29:10,739: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:29:10] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:29:16,736: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 43, in predictRoute
    return jsonify(result)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\json\provider.py", line 215, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type ndarray is not JSON serializable
[2023-07-24 19:29:16,787: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:29:16] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-24 19:30:36,962: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 19:30:36,962: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 19:30:38,854: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:30:38] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:30:44,471: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:30:44] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:31:30,664: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 19:31:30,664: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 19:31:34,367: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:31:34] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:31:42,510: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:31:42] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:33:59,743: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 19:33:59,743: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 19:34:01,655: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:34:01] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:34:11,450: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:34:11] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:34:52,002: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:34:52] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:35:08,748: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:35:08] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:35:16,549: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:35:16] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:35:30,848: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000016286F14430> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-07-24 19:35:30,849: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:35:30] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:35:36,582: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000016286F15510> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-07-24 19:35:36,582: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:35:36] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:37:25,581: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 19:37:25,581: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 19:37:27,701: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:37:27] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:37:33,429: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:37:33] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:37:51,646: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:37:51] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:37:54,478: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:37:54] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:37:55,700: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:37:55] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:38:03,113: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:38:03] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:38:29,100: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 19:38:29,100: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 19:38:32,011: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:38:32] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:38:37,848: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:38:37] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:39:20,994: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:39:20] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:39:28,283: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:39:28] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:41:13,977: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 19:41:13,977: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 19:41:16,781: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:41:16] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:41:22,893: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:41:22] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:42:33,211: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 19:42:33,216: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 19:42:35,177: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:42:35] "GET / HTTP/1.1" 200 -]
[2023-07-24 19:42:40,942: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 19:42:40] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 19:43:17,655: INFO: main: >>>>>>> Stage Data Ingestion Stage Started <<<<<<<]
[2023-07-24 19:43:17,664: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-24 19:43:17,664: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-24 19:43:17,664: INFO: common: created directory at: artifacts]
[2023-07-24 19:43:17,664: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-24 19:43:17,664: INFO: data_ingestion: File already exists of size: ~ 2405630 KB]
[2023-07-24 19:43:46,998: INFO: main: >>>>>>> Stage Data Ingestion Stage Completed <<<<<<</n/nx====================x]
[2023-07-24 19:43:46,998: INFO: main: ************************]
[2023-07-24 19:43:46,999: INFO: main: >>>>>>> Stage Training Stage Started <<<<<<<]
[2023-07-24 19:43:47,003: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-24 19:43:47,004: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-24 19:43:47,004: INFO: common: created directory at: artifacts]
[2023-07-24 19:43:47,005: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-24 19:43:47,005: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-24 19:43:47,005: INFO: common: created directory at: artifacts\training]
[2023-07-24 20:23:12,214: INFO: main: >>>>>>> Stage Training Stage Completed <<<<<<<

x====================x]
[2023-07-24 20:35:50,028: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 20:35:50,028: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 20:35:54,355: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 20:35:54] "GET / HTTP/1.1" 200 -]
[2023-07-24 20:36:16,285: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 20:36:16] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 20:36:27,672: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 20:36:27] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 20:50:29,542: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 20:50:29,542: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 20:50:32,328: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 20:50:32] "GET / HTTP/1.1" 200 -]
[2023-07-24 20:50:41,638: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 42, in predictRoute
    result = prediction_pipeline.predict()
  File "C:\Programs\xray\src\xray\pipeline\predict.py", line 25, in predict
    predicted_label = labels[int(np.round(prediction[0][0]+1))]
IndexError: list index out of range
[2023-07-24 20:50:41,648: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 20:50:41] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-24 20:52:34,853: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 20:52:34,853: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 20:52:37,937: INFO: _internal: 192.168.196.107 - - [24/Jul/2023 20:52:37] "GET / HTTP/1.1" 200 -]
[2023-07-24 20:52:48,637: INFO: _internal: 192.168.196.107 - - [24/Jul/2023 20:52:48] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 20:52:59,103: INFO: _internal: 192.168.196.107 - - [24/Jul/2023 20:52:59] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 20:54:54,141: INFO: _internal: 192.168.196.107 - - [24/Jul/2023 20:54:54] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 20:55:21,002: INFO: _internal: 192.168.196.107 - - [24/Jul/2023 20:55:21] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 20:57:17,220: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002C4B1320550> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-07-24 20:57:17,233: INFO: _internal: 192.168.196.107 - - [24/Jul/2023 20:57:17] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:02:30,967: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 21:02:30,967: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 21:04:02,842: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:04:02] "GET / HTTP/1.1" 200 -]
[2023-07-24 21:04:17,407: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:04:17] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:05:30,858: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:05:30] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:09:59,520: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 21:09:59,520: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 21:10:01,700: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:10:01] "GET / HTTP/1.1" 200 -]
[2023-07-24 21:10:10,718: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:10:10] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:10:21,986: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:10:21] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:10:33,539: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:10:33] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:10:40,720: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:10:40] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:11:01,562: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 21:11:01,562: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 21:11:04,208: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:11:04] "GET / HTTP/1.1" 200 -]
[2023-07-24 21:11:15,999: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:11:15] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:12:10,317: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:12:10] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:12:58,798: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 21:12:58,798: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 21:13:01,739: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:13:01] "GET / HTTP/1.1" 200 -]
[2023-07-24 21:13:14,716: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:13:14] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:15:20,165: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 21:15:20,165: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 21:15:22,386: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:15:22] "GET / HTTP/1.1" 200 -]
[2023-07-24 21:15:34,080: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 42, in predictRoute
    result = prediction_pipeline.predict()
  File "C:\Programs\xray\src\xray\pipeline\predict.py", line 18, in predict
    image = load_img(self.filename, target_size=(150, 150))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'inputImage.jpg'
[2023-07-24 21:15:34,097: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:15:34] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-24 21:16:16,072: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 21:16:16,072: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 21:16:21,149: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:16:21] "GET / HTTP/1.1" 200 -]
[2023-07-24 21:16:32,263: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 42, in predictRoute
    result = prediction_pipeline.predict()
  File "C:\Programs\xray\src\xray\pipeline\predict.py", line 18, in predict
    image = load_img(self.filename, target_size=(150, 150))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'inputImage.jpg'
[2023-07-24 21:16:32,278: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:16:32] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-24 21:17:07,963: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 21:17:07,963: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 21:17:10,417: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:17:10] "GET / HTTP/1.1" 200 -]
[2023-07-24 21:17:23,060: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Programs\xray\app.py", line 42, in predictRoute
    result = prediction_pipeline.predict()
  File "C:\Programs\xray\src\xray\pipeline\predict.py", line 18, in predict
    image = load_img(self.filename, target_size=(150, 150))
  File "C:\Users\Sandesh Pargaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\image_utils.py", line 422, in load_img
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'inputImage.jpg'
[2023-07-24 21:17:23,078: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:17:23] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-07-24 21:17:57,743: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:17:57] "GET / HTTP/1.1" 200 -]
[2023-07-24 21:18:07,777: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:18:07] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:20:33,066: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 21:20:33,066: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 21:20:35,524: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:20:35] "GET / HTTP/1.1" 200 -]
[2023-07-24 21:20:43,207: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:20:43] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:20:57,112: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:20:57] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:21:04,854: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:21:04] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:21:14,406: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:21:14] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:29:43,359: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-24 21:29:43,359: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-24 21:29:46,153: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:29:46] "GET / HTTP/1.1" 200 -]
[2023-07-24 21:29:55,413: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:29:55] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:30:16,919: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:30:16] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:30:33,938: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:30:33] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:30:47,185: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:30:47] "POST /predict HTTP/1.1" 200 -]
[2023-07-24 21:31:24,961: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D7A15144C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-07-24 21:31:24,968: INFO: _internal: 127.0.0.1 - - [24/Jul/2023 21:31:24] "POST /predict HTTP/1.1" 200 -]
[2023-07-25 19:46:19,328: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-25 19:46:19,328: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-25 19:46:24,817: INFO: _internal: 127.0.0.1 - - [25/Jul/2023 19:46:24] "GET / HTTP/1.1" 200 -]
[2023-07-25 19:54:11,110: INFO: _internal: 127.0.0.1 - - [25/Jul/2023 19:54:11] "POST /predict HTTP/1.1" 200 -]
[2023-07-25 19:54:48,292: INFO: _internal: 127.0.0.1 - - [25/Jul/2023 19:54:48] "POST /predict HTTP/1.1" 200 -]
[2023-07-25 20:12:47,803: INFO: _internal: 127.0.0.1 - - [25/Jul/2023 20:12:47] "POST /predict HTTP/1.1" 200 -]
[2023-07-25 20:13:04,819: INFO: _internal: 127.0.0.1 - - [25/Jul/2023 20:13:04] "POST /predict HTTP/1.1" 200 -]
[2023-07-26 15:17:40,398: INFO: ingestion_pipeline: ************************]
[2023-07-26 15:17:40,398: INFO: ingestion_pipeline: >>>>>>> Stage Data Ingestion Stage Started <<<<<<<]
[2023-07-26 15:17:40,414: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-26 15:17:40,419: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-26 15:17:40,419: INFO: common: created directory at: artifacts]
[2023-07-26 15:17:40,419: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-26 15:17:40,424: INFO: data_ingestion: File already exists of size: ~ 2405630 KB]
[2023-07-26 15:18:53,897: INFO: ingestion_pipeline: >>>>>>> Stage Data Ingestion Stage Completed <<<<<<<

************************]
[2023-07-26 15:30:41,325: INFO: training_pipeline: >>>>>>> Stage Training Stage Started <<<<<<<]
[2023-07-26 15:30:41,340: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-26 15:30:41,344: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-26 15:30:41,344: INFO: common: created directory at: artifacts]
[2023-07-26 15:30:41,344: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-26 15:30:41,349: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-26 15:30:41,349: INFO: common: created directory at: artifacts\training]
[2023-07-26 15:30:41,351: ERROR: training_pipeline: TrainingConfig.__init__() missing 1 required positional argument: 'updated_base_model_path']
Traceback (most recent call last):
  File "C:\Programs\xray\src\xray\pipeline\training_pipeline.py", line 38, in <module>
    obj.main()
  File "C:\Programs\xray\src\xray\pipeline\training_pipeline.py", line 18, in main
    training_config = config.get_training_config()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\programs\xray\src\xray\config\configuration.py", line 82, in get_training_config
    training_config=TrainingConfig(
                    ^^^^^^^^^^^^^^^
TypeError: TrainingConfig.__init__() missing 1 required positional argument: 'updated_base_model_path'
[2023-07-26 15:32:08,992: INFO: main: >>>>>>> Stage Data Ingestion Stage Started <<<<<<<]
[2023-07-26 15:32:09,004: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-26 15:32:09,004: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-26 15:32:09,004: INFO: common: created directory at: artifacts]
[2023-07-26 15:32:09,004: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-26 15:32:09,004: INFO: data_ingestion: File already exists of size: ~ 2405630 KB]
[2023-07-26 15:33:23,114: INFO: main: >>>>>>> Stage Data Ingestion Stage Completed <<<<<<</n/nx====================x]
[2023-07-26 15:33:23,114: INFO: main: ************************]
[2023-07-26 15:33:23,114: INFO: main: >>>>>>> Stage Training Stage Started <<<<<<<]
[2023-07-26 15:33:23,124: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-26 15:33:23,130: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-26 15:33:23,131: INFO: common: created directory at: artifacts]
[2023-07-26 15:33:23,132: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-26 15:33:23,132: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-26 15:33:23,132: INFO: common: created directory at: artifacts\training]
[2023-07-26 15:33:23,132: ERROR: main: TrainingConfig.__init__() missing 1 required positional argument: 'updated_base_model_path']
Traceback (most recent call last):
  File "C:\Programs\xray\main.py", line 26, in <module>
    obj.main()
  File "c:\programs\xray\src\xray\pipeline\training_pipeline.py", line 18, in main
    training_config = config.get_training_config()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\programs\xray\src\xray\config\configuration.py", line 63, in get_training_config
    training_config=TrainingConfig(
                    ^^^^^^^^^^^^^^^
TypeError: TrainingConfig.__init__() missing 1 required positional argument: 'updated_base_model_path'
[2023-07-26 15:34:39,522: INFO: main: >>>>>>> Stage Data Ingestion Stage Started <<<<<<<]
[2023-07-26 15:34:39,535: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-26 15:34:39,542: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-26 15:34:39,543: INFO: common: created directory at: artifacts]
[2023-07-26 15:34:39,547: INFO: common: created directory at: artifacts/data_ingestion]
[2023-07-26 15:34:39,548: INFO: data_ingestion: File already exists of size: ~ 2405630 KB]
[2023-07-26 15:36:00,728: INFO: main: >>>>>>> Stage Data Ingestion Stage Completed <<<<<<</n/nx====================x]
[2023-07-26 15:36:00,729: INFO: main: ************************]
[2023-07-26 15:36:00,729: INFO: main: >>>>>>> Stage Training Stage Started <<<<<<<]
[2023-07-26 15:36:00,741: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-26 15:36:00,744: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-26 15:36:00,744: INFO: common: created directory at: artifacts]
[2023-07-26 15:36:00,744: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-26 15:36:00,744: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-26 15:36:00,751: INFO: common: created directory at: artifacts\training]
[2023-07-26 15:48:46,574: INFO: main: >>>>>>> Stage Training Stage Completed <<<<<<<

x====================x]
[2023-07-26 15:55:59,363: INFO: training_pipeline: >>>>>>> Stage Training Stage Started <<<<<<<]
[2023-07-26 15:55:59,377: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-26 15:55:59,385: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-26 15:55:59,385: INFO: common: created directory at: artifacts]
[2023-07-26 15:55:59,385: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-26 15:55:59,385: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-26 15:55:59,385: INFO: common: created directory at: artifacts\training]
[2023-07-26 16:07:23,223: INFO: training_pipeline: >>>>>>> Stage Training Stage Completed <<<<<<<

************************]
[2023-07-26 17:15:47,029: INFO: training_pipeline: >>>>>>> Stage Training Stage Started <<<<<<<]
[2023-07-26 17:15:47,044: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-07-26 17:15:47,049: INFO: common: yaml file: params.yaml loaded successfully]
[2023-07-26 17:15:47,051: INFO: common: created directory at: artifacts]
[2023-07-26 17:15:47,052: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-07-26 17:15:47,052: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-07-26 17:15:47,052: INFO: common: created directory at: artifacts\training]
[2023-07-26 18:18:24,302: INFO: training_pipeline: >>>>>>> Stage Training Stage Completed <<<<<<<

************************]
[2023-07-26 21:46:16,213: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.196.107:8080]
[2023-07-26 21:46:16,213: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-07-26 21:46:22,717: INFO: _internal: 127.0.0.1 - - [26/Jul/2023 21:46:22] "GET / HTTP/1.1" 200 -]
